Layout/Tab:
  Enabled: false

Layout/IndentationWidth:
  Width: 1

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/AsciiComments:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FormatStringToken:
  Exclude:
    - 'test/xolti/header/tc_template_utils.rb'

# Necessary to allow 2 blank lines below license headers, in order to prevent Yard
# to recognize them as documentation
Style/EmptyLines:
  Enabled: false
